/*
Daytona Server API

Daytona Server API

API version: v0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ProjectDataDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectDataDTO{}

// ProjectDataDTO struct for ProjectDataDTO
type ProjectDataDTO struct {
	BuildConfig *BuildConfig           `json:"buildConfig,omitempty"`
	EnvVars     map[string]string      `json:"envVars"`
	Image       *string                `json:"image,omitempty"`
	Name        string                 `json:"name"`
	Source      CreateProjectSourceDTO `json:"source"`
	User        *string                `json:"user,omitempty"`
}

type _ProjectDataDTO ProjectDataDTO

// NewProjectDataDTO instantiates a new ProjectDataDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectDataDTO(envVars map[string]string, name string, source CreateProjectSourceDTO) *ProjectDataDTO {
	this := ProjectDataDTO{}
	this.EnvVars = envVars
	this.Name = name
	this.Source = source
	return &this
}

// NewProjectDataDTOWithDefaults instantiates a new ProjectDataDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectDataDTOWithDefaults() *ProjectDataDTO {
	this := ProjectDataDTO{}
	return &this
}

// GetBuildConfig returns the BuildConfig field value if set, zero value otherwise.
func (o *ProjectDataDTO) GetBuildConfig() BuildConfig {
	if o == nil || IsNil(o.BuildConfig) {
		var ret BuildConfig
		return ret
	}
	return *o.BuildConfig
}

// GetBuildConfigOk returns a tuple with the BuildConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDataDTO) GetBuildConfigOk() (*BuildConfig, bool) {
	if o == nil || IsNil(o.BuildConfig) {
		return nil, false
	}
	return o.BuildConfig, true
}

// HasBuildConfig returns a boolean if a field has been set.
func (o *ProjectDataDTO) HasBuildConfig() bool {
	if o != nil && !IsNil(o.BuildConfig) {
		return true
	}

	return false
}

// SetBuildConfig gets a reference to the given BuildConfig and assigns it to the BuildConfig field.
func (o *ProjectDataDTO) SetBuildConfig(v BuildConfig) {
	o.BuildConfig = &v
}

// GetEnvVars returns the EnvVars field value
func (o *ProjectDataDTO) GetEnvVars() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.EnvVars
}

// GetEnvVarsOk returns a tuple with the EnvVars field value
// and a boolean to check if the value has been set.
func (o *ProjectDataDTO) GetEnvVarsOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvVars, true
}

// SetEnvVars sets field value
func (o *ProjectDataDTO) SetEnvVars(v map[string]string) {
	o.EnvVars = v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *ProjectDataDTO) GetImage() string {
	if o == nil || IsNil(o.Image) {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDataDTO) GetImageOk() (*string, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *ProjectDataDTO) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *ProjectDataDTO) SetImage(v string) {
	o.Image = &v
}

// GetName returns the Name field value
func (o *ProjectDataDTO) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProjectDataDTO) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProjectDataDTO) SetName(v string) {
	o.Name = v
}

// GetSource returns the Source field value
func (o *ProjectDataDTO) GetSource() CreateProjectSourceDTO {
	if o == nil {
		var ret CreateProjectSourceDTO
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *ProjectDataDTO) GetSourceOk() (*CreateProjectSourceDTO, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *ProjectDataDTO) SetSource(v CreateProjectSourceDTO) {
	o.Source = v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *ProjectDataDTO) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDataDTO) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *ProjectDataDTO) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *ProjectDataDTO) SetUser(v string) {
	o.User = &v
}

func (o ProjectDataDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectDataDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BuildConfig) {
		toSerialize["buildConfig"] = o.BuildConfig
	}
	toSerialize["envVars"] = o.EnvVars
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	toSerialize["name"] = o.Name
	toSerialize["source"] = o.Source
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	return toSerialize, nil
}

func (o *ProjectDataDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"envVars",
		"name",
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectDataDTO := _ProjectDataDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectDataDTO)

	if err != nil {
		return err
	}

	*o = ProjectDataDTO(varProjectDataDTO)

	return err
}

type NullableProjectDataDTO struct {
	value *ProjectDataDTO
	isSet bool
}

func (v NullableProjectDataDTO) Get() *ProjectDataDTO {
	return v.value
}

func (v *NullableProjectDataDTO) Set(val *ProjectDataDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectDataDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectDataDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectDataDTO(val *ProjectDataDTO) *NullableProjectDataDTO {
	return &NullableProjectDataDTO{value: val, isSet: true}
}

func (v NullableProjectDataDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectDataDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
